version: '3.4'

services:
  techblogdb:
   image: mcr.microsoft.com/mssql/server
 
  techblogtestdb:
   image: mcr.microsoft.com/mssql/server
  
  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: Services/Blog/Blog.API/Dockerfile
