version: '3.4'

services:
 techblogdb:
  container_name: techblogdb
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=SA#123456
  restart: always
  ports:
   - "1133:1433"

 techblogtestdb:
  container_name: techblogtestdb
  environment:
   - ACCEPT_EULA=Y
   - SA_PASSWORD=SA#123456
  restart: always
  ports:
   - "1233:1433"

 blog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=techblogdb;Database=techblogdb;User id=sa;Password=SA#123456;Encrypt=False;TrustServerCertificate=True
    ports:
      - "6005:8080"
      - "6055:8081"
    depends_on:
     - techblogdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

 elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch-data:/usr/share/elasticsearch/data

 kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200/
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"